# Protocol-level metadata used across the risk engine.
# Static fields (audit history, exploit record, governance structure) are sourced
# from DefiSafety, Certik, protocol docs, and post-mortems — updated as of Q1 2026.

WEIGHTS = {
    "liquidity":     0.25,
    "market":        0.20,
    "smart_contract":0.25,
    "governance":    0.20,
    "sentiment":     0.10,
}

# Risk score bands (composite 0-100, lower = safer)
THRESHOLDS = {
    "low":    35,
    "medium": 60,
}

# DeFiLlama API slug overrides (slug != lowercased name)
SLUG_OVERRIDES = {
    "Sky (MakerDAO)":  "makerdao",
    "1Inch":           "1inch",
    "Curve Finance":   "curve-dex",
    "Compound":        "compound-v2",
    "Convex Finance":  "convex-finance",
    "Frax Finance":    "frax",
    "PancakeSwap":     "pancakeswap",
    "Beefy Finance":   "beefy",
    "Yearn Finance":   "yearn-finance",
    "Kamino Finance":  "kamino",
    "GMX":             "gmx",
    "JustLend":        "justlend",
    "Instadapp":       "fluid-lending",
}

# Per-protocol static risk metadata.
# exploit_severity: 0=none, 1=minor/indirect, 2=direct major exploit
# token_gini: 0–1 concentration estimate from governance token distribution analysis
# audit_age_days: approximate days since most recent comprehensive external audit (as of Apr 2026)
PROTOCOLS = {
    "Lido": {
        "category":        "Liquid Staking",
        "chain":           "Ethereum",
        "coingecko_id":    "lido-dao",
        "token":           "LDO",
        "audit_age_days":  210,
        "exploit_severity":0,
        "bug_bounty_usd":  2_000_000,
        "has_timelock":    True,
        "timelock_days":   2,
        "token_gini":      0.72,
        "chains_count":    2,
        "eth_exposure":    True,
    },
    "Sky (MakerDAO)": {
        "category":        "CDP",
        "chain":           "Ethereum",
        "coingecko_id":    "maker",
        "token":           "MKR",
        "audit_age_days":  90,
        "exploit_severity":0,
        "bug_bounty_usd":  10_000_000,
        "has_timelock":    True,
        "timelock_days":   2,
        "token_gini":      0.65,
        "chains_count":    1,
        "eth_exposure":    True,
    },
    "Aave": {
        "category":        "Lending",
        "chain":           "Multi-chain",
        "coingecko_id":    "aave",
        "token":           "AAVE",
        "audit_age_days":  60,
        "exploit_severity":0,
        "bug_bounty_usd":  2_500_000,
        "has_timelock":    True,
        "timelock_days":   1,
        "token_gini":      0.55,
        "chains_count":    8,
        "eth_exposure":    True,
    },
    "JustLend": {
        "category":        "Lending",
        "chain":           "TRON",
        "coingecko_id":    "tron",
        "token":           "TRX",
        "audit_age_days":  420,
        "exploit_severity":0,
        "bug_bounty_usd":  0,
        "has_timelock":    False,
        "timelock_days":   0,
        "token_gini":      0.91,   # Justin Sun / TRON Foundation concentration
        "chains_count":    1,
        "eth_exposure":    False,
    },
    "Uniswap": {
        "category":        "DEX",
        "chain":           "Multi-chain",
        "coingecko_id":    "uniswap",
        "token":           "UNI",
        "audit_age_days":  150,
        "exploit_severity":0,
        "bug_bounty_usd":  2_250_000,
        "has_timelock":    True,
        "timelock_days":   2,
        "token_gini":      0.60,
        "chains_count":    10,
        "eth_exposure":    True,
    },
    "PancakeSwap": {
        "category":        "DEX",
        "chain":           "BNB Chain",
        "coingecko_id":    "pancakeswap-token",
        "token":           "CAKE",
        "audit_age_days":  240,
        "exploit_severity":1,
        "bug_bounty_usd":  500_000,
        "has_timelock":    True,
        "timelock_days":   1,
        "token_gini":      0.70,
        "chains_count":    3,
        "eth_exposure":    False,
    },
    "Convex Finance": {
        "category":        "Yield Aggregator",
        "chain":           "Ethereum",
        "coingecko_id":    "convex-finance",
        "token":           "CVX",
        "audit_age_days":  630,
        "exploit_severity":0,
        "bug_bounty_usd":  250_000,
        "has_timelock":    True,
        "timelock_days":   1,
        "token_gini":      0.68,
        "chains_count":    1,
        "eth_exposure":    True,
    },
    "Curve Finance": {
        "category":        "DEX",
        "chain":           "Multi-chain",
        "coingecko_id":    "curve-dao-token",
        "token":           "CRV",
        "audit_age_days":  270,
        "exploit_severity":2,   # July 2023 Vyper reentrancy — ~$70M
        "bug_bounty_usd":  250_000,
        "has_timelock":    True,
        "timelock_days":   1,
        "token_gini":      0.75,
        "chains_count":    7,
        "eth_exposure":    True,
    },
    "Compound": {
        "category":        "Lending",
        "chain":           "Ethereum",
        "coingecko_id":    "compound-governance-token",
        "token":           "COMP",
        "audit_age_days":  740,
        "exploit_severity":1,   # 2021 oracle price manipulation
        "bug_bounty_usd":  150_000,
        "has_timelock":    True,
        "timelock_days":   2,
        "token_gini":      0.58,
        "chains_count":    2,
        "eth_exposure":    True,
    },
    "Instadapp": {
        "category":        "Asset Management",
        "chain":           "Multi-chain",
        "coingecko_id":    "instadapp",
        "token":           "INST",
        "audit_age_days":  150,
        "exploit_severity":0,
        "bug_bounty_usd":  100_000,
        "has_timelock":    True,
        "timelock_days":   1,
        "token_gini":      0.62,
        "chains_count":    4,
        "eth_exposure":    True,
    },
    "Aerodrome": {
        "category":        "DEX",
        "chain":           "Base",
        "coingecko_id":    "aerodrome-finance",
        "token":           "AERO",
        "audit_age_days":  120,
        "exploit_severity":0,
        "bug_bounty_usd":  100_000,
        "has_timelock":    True,
        "timelock_days":   1,
        "token_gini":      0.58,
        "chains_count":    1,
        "eth_exposure":    True,
    },
    "Kamino Finance": {
        "category":        "Yield Aggregator",
        "chain":           "Solana",
        "coingecko_id":    "kamino",
        "token":           "KMNO",
        "audit_age_days":  200,
        "exploit_severity":0,
        "bug_bounty_usd":  100_000,
        "has_timelock":    False,
        "timelock_days":   0,
        "token_gini":      0.65,
        "chains_count":    1,
        "eth_exposure":    False,
    },
    "Beefy Finance": {
        "category":        "Yield Aggregator",
        "chain":           "Multi-chain",
        "coingecko_id":    "beefy-finance",
        "token":           "BIFI",
        "audit_age_days":  300,
        "exploit_severity":1,
        "bug_bounty_usd":  50_000,
        "has_timelock":    True,
        "timelock_days":   1,
        "token_gini":      0.55,
        "chains_count":    15,
        "eth_exposure":    False,
    },
    "Frax Finance": {
        "category":        "Stablecoin/LSD",
        "chain":           "Multi-chain",
        "coingecko_id":    "frax-share",
        "token":           "FXS",
        "audit_age_days":  250,
        "exploit_severity":0,
        "bug_bounty_usd":  200_000,
        "has_timelock":    True,
        "timelock_days":   1,
        "token_gini":      0.70,
        "chains_count":    5,
        "eth_exposure":    True,
    },
    "GMX": {
        "category":        "Derivatives",
        "chain":           "Arbitrum/Avalanche",
        "coingecko_id":    "gmx",
        "token":           "GMX",
        "audit_age_days":  210,
        "exploit_severity":0,
        "bug_bounty_usd":  500_000,
        "has_timelock":    True,
        "timelock_days":   1,
        "token_gini":      0.60,
        "chains_count":    2,
        "eth_exposure":    True,
    },
    "Yearn Finance": {
        "category":        "Yield Aggregator",
        "chain":           "Ethereum",
        "coingecko_id":    "yearn-finance",
        "token":           "YFI",
        "audit_age_days":  850,
        "exploit_severity":2,   # Feb 2023 flash loan attack — $11.6M
        "bug_bounty_usd":  200_000,
        "has_timelock":    True,
        "timelock_days":   1,
        "token_gini":      0.55,
        "chains_count":    3,
        "eth_exposure":    True,
    },
    "Jupiter": {
        "category":        "DEX Aggregator",
        "chain":           "Solana",
        "coingecko_id":    "jup",
        "token":           "JUP",
        "audit_age_days":  60,
        "exploit_severity":0,
        "bug_bounty_usd":  1_000_000,
        "has_timelock":    False,
        "timelock_days":   0,
        "token_gini":      0.60,
        "chains_count":    1,
        "eth_exposure":    False,
    },
    "Solend": {
        "category":        "Lending",
        "chain":           "Solana",
        "coingecko_id":    "solend",
        "token":           "SLND",
        "audit_age_days":  730,
        "exploit_severity":1,   # 2022 whale liquidation governance controversy
        "bug_bounty_usd":  100_000,
        "has_timelock":    False,
        "timelock_days":   0,
        "token_gini":      0.68,
        "chains_count":    1,
        "eth_exposure":    False,
    },
    "Synthetix": {
        "category":        "Derivatives",
        "chain":           "Optimism/Ethereum",
        "coingecko_id":    "havven",
        "token":           "SNX",
        "audit_age_days":  90,
        "exploit_severity":1,
        "bug_bounty_usd":  1_500_000,
        "has_timelock":    True,
        "timelock_days":   1,
        "token_gini":      0.60,
        "chains_count":    3,
        "eth_exposure":    True,
    },
    "1Inch": {
        "category":        "DEX Aggregator",
        "chain":           "Multi-chain",
        "coingecko_id":    "1inch",
        "token":           "1INCH",
        "audit_age_days":  250,
        "exploit_severity":0,
        "bug_bounty_usd":  500_000,
        "has_timelock":    True,
        "timelock_days":   1,
        "token_gini":      0.62,
        "chains_count":    6,
        "eth_exposure":    True,
    },
}

# Stablecoin-exposed protocols (for depeg stress scenario)
STABLECOIN_EXPOSED = {
    "Curve Finance", "Sky (MakerDAO)", "Aave", "Compound",
    "Frax Finance", "Convex Finance", "Instadapp",
}

# ETH-collateral-heavy protocols (for ETH crash scenario)
ETH_COLLATERAL_HEAVY = {
    "Aave", "Compound", "Sky (MakerDAO)", "Lido",
    "Instadapp", "Synthetix",
}

CATEGORY_COLORS = {
    "Lending":          "#58a6ff",
    "DEX":              "#3fb950",
    "Liquid Staking":   "#d2a8ff",
    "CDP":              "#ffa657",
    "Yield Aggregator": "#79c0ff",
    "Derivatives":      "#ff7b72",
    "Stablecoin/LSD":   "#f0883e",
    "DEX Aggregator":   "#56d364",
    "Asset Management": "#e3b341",
}
